version: '3'
services:
  neo4j:
    image: neo4j:4.4.15-enterprise
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./validalab:/data
      - ./logs:/logs
      - ./conf:/var/lib/neo4j/conf/
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    
      
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
        - 8888:8888
    volumes:
        - .:/home/jovyan/work
    environment:
        JUPYTER_ENABLE_LAB: "yes"